- name: Install tomcat8 using apt or yum
  hosts: all
  tasks:
   - block:
      - name: Install tomcat8 using apt
        apt:
         name: tomcat7
         state: present
     rescue:
      - name: Install tomcat8 using yum 
        apt:
         name: tomcat8
         state: present
     always:
       - name: check
         uri:
          url: "{{item}}"
          status_code: 200
       #with_items:
        #- http://172.31.22.188:8080
        #- http://172.31.21.26:8080
