- name: install softwares
  hosts: devserver
  tasks:
   - name: install java,git,maven
     apt: 
      name: "{{item}}"
      state: present
     with_items:
      - openjdk-8-jdk
      - git
      - maven
   - name: download jenkins
     get_url:
      url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
      dest: /tmp       
   - name: start jenkins   
     shell: java -jar /tmp/jenkins.war
- name: install tomcat8 and tomcat8-admin        
  hosts: qaserver
  tasks:
   - name: install tomcat8,tomcar8-admin
     apt:
      name: "{{item}}"       
      state: present
     with_items: 
      - tomcat8
      - tomcat8-admin
   - name: copy tomcat-users.xml
     copy:
      src: /home/ubuntu/tomcat-users.xml
      dest: /etc/tomcat8
   - name: restart tomcat8
     service:
      name: tomcat8
      state: restarted       

             
